language: python

sudo: false

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  matrix:
    - PEP=false

matrix:
  include:
    - python: 2.7
      env: PEP=true

install:
  - pip install pep8
  - pip install .

script:
    - if $PEP; then pep8 notedown; fi
    - if ! $PEP; then nosetests; fi
